#!/bin/bash

wfdr-cache-monitor -sourcedir="shared/tmpl" -destdir="cache/tmpl" -filetype="tmpl" -mode="deamon" &
tmplmon=$!

wfdr-cache-monitor -sourcedir="shared/css" -destdir="cache/css" -filetype="css" -mode="deamon" &
cssmon=$!

wfdr-cache-monitor -sourcedir="shared/img" -destdir="cache/img" -filetype="img" -mode="deamon" &
imgmon=$!

wfdr-cache-monitor -sourcedir="shared/js" -destdir="cache/js" -filetype="js" -mode="deamon" &
jsmon=$!

trap "kill $tmplmon" SIGINT
trap "kill $cssmon" SIGINT
trap "kill $imgmon" SIGINT
trap "kill $jsmon" SIGINT
