#!/bin/bash
# Used to reload all of the "shared" resources, stored in shared/.

mkdir -p cache/tmpl
mkdir -p cache/css
mkdir -p cache/js

wfdr-cache-monitor -sourcedir="shared/tmpl" -destdir="cache/tmpl" -filetype="tmpl" -mode="sync";

wfdr-cache-monitor -sourcedir="shared/css" -destdir="cache/css" -filetype="css" -mode="sync";

wfdr-cache-monitor -sourcedir="shared/img" -destdir="cache/img" -filetype="img" -mode="sync";

wfdr-cache-monitor -sourcedir="shared/js" -destdir="cache/js" -filetype="js" -mode="sync";
