#!/bin/bash
if [ $# -lt 1 ]; then
	echo "Not enough arguments! Please specify a module name!"
	exit 1
fi

recompile=0
if [ $# -gt 1 ]; then
	if [ $2 = "-recompile" -o $1 = "-recompile" ]; then
		recompile=1
	fi
fi

cd modules/$1

if [ ! -d bin ]; then
	mkdir bin
fi

echo -n "Building module $1: "

if [ -f src/Makefile ]; then
	echo "Using Makefile in src/"
	cd src
	if [ $recompile -eq 1 ]; then
		make clean
	fi
	make
	exit
fi

if ls src/*.go &> /dev/null; then
	echo "Using go build"
	cd src
	# TODO: Recompile logic if required?
	go build -o a.out *.go
	status=$?
	if [ $status -eq 0 ]; then
		cp a.out ../bin/$1
		exit
	fi
	exit $status
fi

echo "No Makefile and no go files found. If this module should be compiled, consider adding a makefile."
exit 1